### ISSUE TITLE
在主界面切换编码格式没反应

### ISSUE THREAD

**Issue by anson2001** [vseasky/VersaAssistant#3]
我研究了一段时间后，发现在 vcodeconverter.c 里  把 vSerialCodeModeEnum vSerialCodeMode = SerialCodeUtf8  改为vSerialCodeModeEnum vSerialCodeMode = SerialCodeGB18030; 就可以支持中文，但是在主界面切换编码格式还是没反应，不知道怎么搞，请多多指教。

**Comment by SEASKY-Master** [comment]
默认就支持中文的啊！不需要改代码，选择GBK就行，重新设置串口参数后如果串口是打开状态要关闭后重新打开串口！！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月27日(星期四) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [SEASKY-Master/vSailorProject] 在主界面切换编码格式没反应 (Issue #3)





 
我研究了一段时间后，发现在 vcodeconverter.c 里  把 vSerialCodeModeEnum vSerialCodeMode = SerialCodeUtf8  改为vSerialCodeModeEnum vSerialCodeMode = SerialCodeGB18030; 就可以支持中文，但是在主界面切换编码格式还是没反应，不知道怎么搞，请多多指教。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SEASKY-Master** [comment]
编码格式可以设置的

**Comment by anson2001** [comment]
- 不行啊，在主界面切换编码格式完成没反应,应该就是一个BUG, 我试了很多次了，原来是支持Utf8 编码的，跟其串口助手一起测试乱码，  vcodeconverter.c 里 把 vSerialCodeModeEnum vSerialCodeMode = SerialCodeUtf8 改为vSerialCodeModeEnum vSerialCodeMode = SerialCodeGB18030 就没有乱码了

**Comment by anson2001** [comment]
<img width="838" alt="1" src="https://user-images.githubusercontent.com/28837702/151509886-aeb960f2-e8ef-429e-9bd8-d1cc680fdbb8.PNG">
<img width="876" alt="2" src="https://user-images.githubusercontent.com/28837702/151510943-e180a531-b4aa-47e7-9778-701dae4c694b.PNG">
<img width="833" alt="3" src="https://user-images.githubusercontent.com/28837702/151510946-157e49a8-2370-4cb5-a468-74d49a319064.PNG">
请看图片的问题，图片1 是修改版程序与原版程序效果对比，出现乱码。 图片2 是修改版程序与SSCOM程序效果对比，无乱码。图片3 是原版程序与SSCOM程序效果对比，有乱码。

**Comment by SEASKY-Master** [comment]
咦，可能是我后期修改了什么地方，没验证这个？我到时候看下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月28日(星期五) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SEASKY-Master/vSailorProject] 在主界面切换编码格式没反应 (Issue #3)





 

 

 

 请看图片的问题，图片1 是修改版程序与原版程序效果对比，出现乱码。 图片2 是修改版程序与SSCOM程序效果对比，无乱码。图片3 是原版程序与SSCOM程序效果对比，有乱码。 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anson2001** [comment]
什么时候把这些问题解决一下，并发布一个新版本呢？

**Comment by anson2001** [comment]
请帮忙没验证这个问题？并发布一个新版本呢？
